# En este fichero mejor no poner caracteres especiales
spring.application.name=EjemploSpringBoot-productos
spring.profiles.active=dev
# En producción debería ser:
# spring.profiles.active=prod
# y en testing:
# spring.profiles.active=test
spring.datasource.url=jdbc:mysql://localhost:3306/productos
spring.datasource.username=root
spring.datasource.password=tu_password
# Evita cargar schema.sql o data.sql aunque estén
# presentes en el proyecto. En producción, la base de datos 
# ya debería estar configurada.
spring.sql.init.mode=never
# Desactivamos Swager y openapi en producción
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false