# En este fichero mejor no poner caracteres especiales, como acentos
spring.application.name=EjemploSpringBoot-productos

# Perfil activo
spring.profiles.active=dev
# En produccion deberia ser:
# spring.profiles.active=prod
# y en testing:
# spring.profiles.active=test

# Una alternativa mejor es definir el perfil activo mediante una
# variable de entorno en bash, de la forma:
# SPRING_PROFILES_ACTIVE=prod
#
# En Spring Boot, las variables de entorno tienen prioridad frente
# a las definiciones de application.properties, pero es conveniente
# tener cuidado, ya nos arriesgamos a exponer endpoints que quizas
# no queramos con Swagger, o utilizar configuraciones de seguridad
# reducidas, etc.